### ISSUE TITLE
React Navigation 3.11.1

### ISSUE THREAD

**Issue by Cchumi** [alex-melnyk/react-native-multibar#15]
Hi I just start to use your version because my own implementation doesn't work on android only.
I cannot click on the small icon nothing happen.

So I just try your library but same thing happen. I think it's a rect navigation version issue.

One other question: Is it possible with your library to make a navigation on the toggle click ?

thanks

**Comment by Benzen8** [comment]
same issue here

**Comment by shekharskamble** [comment]
any luck @Cchumi & @Benzen8?

**Comment by Benzen8** [comment]
@shekharskamble couldn't implement it in a direct approach. But done without using the package.
Creating the required view as a component and enable it in every bottom tab screen. if the component is inactive hide in every screen in the bottom tab. Only problem is during bottom tab click change is not seamless.
