### ISSUE TITLE
App Content covered by the multibar

### ISSUE THREAD

**Issue by rajatgyl** [alex-melnyk/react-native-multibar#17]
Hi,
I am using react-native-multibar in on of my projects and I am facing an issue that the multibar is covering up my app content which is a flatlist and the end data is not showing completely.
![2](https://user-images.githubusercontent.com/48783158/61990383-54a41f80-b05d-11e9-89fe-543e423970e6.png)
![1](https://user-images.githubusercontent.com/48783158/61990384-54a41f80-b05d-11e9-830a-71ab493b1ab2.png)

**Comment by alex-melnyk** [comment]
@rajatgyl Add padding in the **contentContainerStyle**:
```contentContainerStyle={{
  paddingBottom: 80
}}```

**Comment by ajiehatajie** [comment]
> @rajatgyl Add padding in the **contentContainerStyle**:
> 
> ```
> contentContainerStyle={{
>   paddingBottom: 80
> }}
> ```


where the code is placed for  paddingBottom: 80 ?
