### ISSUE TITLE
MultiTab background color and keep bottom bar when click in hidden buttons

### ISSUE THREAD

**Issue by arthurengadv** [alex-melnyk/react-native-multibar#19]
Hi there,

I sucessufly implemented the real-native-multibar with the examples provided.

I would like to know if is possible to change the color of the round add button?

Like these:

<img width="501" alt="PREVIEW_COLLAPSED copy" src="https://user-images.githubusercontent.com/53925680/62891404-00b35f00-bd1c-11e9-9ca4-113b2336d5a3.png">

Another question is if is possible to keep the bar when I click the other hidden buttons. I see that if I click I go to a page without return. I know that I can create a "back"button, but I would like to keep that tab to be able to click and go to others views without clicking the back button.

Thanks in advance!

**Comment by alex-melnyk** [comment]
Hi, you can it with properties, please check MultyBarToggle file.

https://github.com/alex-melnyk/react-native-multibar/blob/master/src/components/MultiBarToggle.js

**Comment by arthurengadv** [comment]
Thanks! Solved the color issue with the following props:

`
...
MultiBar: {
        screen: () => null,
        navigationOptions: ({navigation}) => ({
            tabBarIcon: () => (
                <MultiBarToggle
                    **toggleColor={'#171F33'}**
                    navigation={navigation}
                    actionSize={30}
...
`
