### ISSUE TITLE
Android doesn't fire actions

### ISSUE THREAD

**Issue by gasparteixeira** [alex-melnyk/react-native-multibar#2]
Hi Alex, 

Firstly, thank you for that brilliant job. I am using Expo with last version of navigation and my android test phone is not firing actions. It seems that navigation bar bottom has no overflow enabled. iOS works perfectly!

**Comment by Sonic-Ninja** [comment]
@gasparteixeira 
  I just submitted a merge request that fixed it for me using the below answer with createAnimatedComponent. 

Hope it helps. 

[https://stackoverflow.com/questions/32738296/how-to-make-react-native-animated-view-clickable](url)

**Comment by gasparteixeira** [comment]
@Sonic-Ninja 
I tried your solution. Still not firing yet. But it's seems to be an issue with Android and overflow!

**Comment by alex-melnyk** [comment]
Please try the latest version of lib [react-native-multibar@0.0.5](https://www.npmjs.com/package/react-native-multibar).

**Comment by rahulp-nimblechapps** [comment]
if you're using NavigationStack for bottomNavigation and then adding your multibarToggle then you have to use  
**tabBarComponent: MultiBar** so then it will fire action on any click of toggle menu icon.
