### ISSUE TITLE
Close multi bar options when click outside

### ISSUE THREAD

**Issue by huylv-teko** [alex-melnyk/react-native-multibar#21]
Hi, is there any prop to make multi bar options close when user open and click outside, if not, it still open when they change tab, this is not good UX

**Comment by alex-melnyk** [comment]
> Hi, is there any prop to make multi bar options close when user open and click outside, if not, it still open when they change tab, this is not good UX

Hi @huylv-teko actually I had solved this problem before, could you provide more details about version s of libraries which you are using and devices

**Comment by huylv-teko** [comment]
> > Hi, is there any prop to make multi bar options close when user open and click outside, if not, it still open when they change tab, this is not good UX
> 
> Hi @huylv-teko actually I had solved this problem before, could you provide more details about version s of libraries which you are using and devices

I run your demo using expo, it used react-native-multibar 0.0.12, and when i clicked change tab, the MultiBarToggle still open

**Comment by alex-melnyk** [comment]
> > > Hi, is there any prop to make multi bar options close when user open and click outside, if not, it still open when they change tab, this is not good UX
> > 
> > 
> > Hi @huylv-teko actually I had solved this problem before, could you provide more details about version s of libraries which you are using and devices
> 
> I run your demo using expo, it used react-native-multibar 0.0.12, and when i clicked change tab, the MultiBarToggle still open

MultiBarToggle has showOverlay property which you can use for this.
