### ISSUE TITLE
Usage for React Navigation 5 [Question]

### ISSUE THREAD

**Issue by ozankonur** [alex-melnyk/react-native-multibar#23]
Hi, is there any sample for React Navigation 5 ?

**Comment by SyedShahbazHussain** [comment]
Waiting for example sample of React Navigation 5....?

**Comment by tylerthedeveloper** [comment]
+1 👍

**Comment by tylerthedeveloper** [comment]
undefined is not an object (evaluating '_navigation$state.index')
- node_modules\react-native-multibar\src\components\MultiBar.js:15:6 in MultiBar

This is in V5

**Comment by alex-melnyk** [comment]
I've update library to use with react-navigation v5

**Comment by SyedShahbazHussain** [comment]
> I've update library to use with react-navigation v5

Thank you
