### ISSUE TITLE
Bug: when navigating using the `MultiBarToggle`, a navigation error is thrown

### ISSUE THREAD

**Issue by mrousavy** [alex-melnyk/react-native-multibar#25]
Navigation using the `MultiBarToggle` does not work, error thrown:
![Screenshot 2020-03-24 at 12 10 33](https://user-images.githubusercontent.com/15199031/77419348-8b872c80-6dc8-11ea-8e27-c0791757fe0b.png)

Reason being a wrong parameter name in the `payload`:
![Screenshot 2020-03-24 at 12 09 05](https://user-images.githubusercontent.com/15199031/77419355-8e821d00-6dc8-11ea-93fa-d4ab0b6a75ad.png)

It expects a `name` or `key` but only `routeName` is supplied. See: [Upgrading from 4.x | React Navigation](https://reactnavigation.org/docs/upgrading-from-4.x#navigate)

**Comment by mrousavy** [comment]
Solution: pull request https://github.com/alex-melnyk/react-native-multibar/pull/26

**Comment by alex-melnyk** [comment]
Fixed by your suggestion.
