### ISSUE TITLE
"renderIcon is not a function" when upgrading to React Navigation v5

### ISSUE THREAD

**Issue by vdyagilev** [alex-melnyk/react-native-multibar#28]
`renderIcon is not a function. (In 'renderIcon({
      route: route,
      focused: focused,
      tintColor: focused ? activeTintColor : inactiveTintColor
    })', 'renderIcon' is undefined)
`

**Comment by vdyagilev** [comment]
The current version does not seem to support React Navigation v5 in other ways too. For example,
`const MultiBar = ({ style, navigation, activeTintColor, inactiveTintColor, renderIcon, jumpTo }) => {
  const {
    index,
    routes
  } = navigation.state;`
throws an error because navigation.state has been replaced by getDangerouslyState() and renderIcon is undefined.

**Comment by tylerthedeveloper** [comment]
@vdyagilev  want to team up and try to fix it?

**Comment by vdyagilev** [comment]
Sure, the author posted an example of using Multibar with the react
navigation 5 syntax, but the code won’t compile because renderIcon function
is missing. I fixed this on my end by creating my own renderIcon function
and passing it in as a parameter.

**Comment by vdyagilev** [comment]
Additionally, the code must be refactored because the parameters passed to
components are different in react nav 5, most notably state is now
dangerouslyGetState() and route is no longer in state.routes but passed
alongside state.

**Comment by yksa** [comment]
Hi ghost, I am also facing the same issue. How did you pass your own renderIcon function?
