### ISSUE TITLE
View beneath Navigation Bar

### ISSUE THREAD

**Issue by destinybonavita** [alex-melnyk/react-native-multibar#33]
I'm using `react-native-multibar` in my React Native project and I had noticed that if I have a ScrollView in a component being displayed, it goes underneath the Navigation Bar. I thought it was an issue with `react-navigation` but as I was reproducing it, I had determined it's probably caused by `react-native-multibar`.

Here's the issue I created in `react-navigation` https://github.com/react-navigation/react-navigation/issues/8327
Here's the snack of it being reproduced https://snack.expo.io/@destinybonavita/disrespectful-french-fries

**Comment by alex-melnyk** [comment]
> I'm using `react-native-multibar` in my React Native project and I had noticed that if I have a ScrollView in a component being displayed, it goes underneath the Navigation Bar. I thought it was an issue with `react-navigation` but as I was reproducing it, I had determined it's probably caused by `react-native-multibar`.
> 
> Here's the issue I created in `react-navigation` [react-navigation/react-navigation#8327](https://github.com/react-navigation/react-navigation/issues/8327)
> Here's the snack of it being reproduced https://snack.expo.io/@destinybonavita/disrespectful-french-fries

Yeah, module overlaps your screens, so the best solution is to add padding to the bottom of scroll view eg:

```<ScrollView contentContainerStyle={{ paddingBottom: 50, }}>...</>```

**Comment by destinybonavita** [comment]
Is there a way to set the padding to the exact height of the overlay?

**Comment by destinybonavita** [comment]
Hi @alex-melnyk, I think I came up for a good solution for this. 
If you modify [this class](https://github.com/alex-melnyk/react-native-multibar/blob/master/src/components/BottomTabBarWrapper/index.tsx) to have the below code it fixes the issue without having to add the padding

```javascript
import { MultiBarOverlay } from 'react-native-multibar';
import { View, Dimensions } from 'react-native';
import * as React from 'react';

const { width } = Dimensions.get('screen')

type Props = Pick<MultiBarPassThroughParams, 'params'>;

export const BottomTabBarWrapper: React.FC<Props> = ({
    children,
    params
}) => (
        <View pointerEvents="box-none" >
            <View style={{ position: 'absolute', bottom: 0, left: 0, width: width, justifyContent: 'flex-end' }}>
                <MultiBarOverlay params={params} />
            </View>
            {children}
        </View>
    );
```

**Comment by destinybonavita** [comment]
There would have to be some bottom padding added to the view to make sure it's above the tab bar but for the most part it works great.
