### ISSUE TITLE
Animated: `useNativeDriver` was not specified.

### ISSUE THREAD

**Issue by lakinduakash** [alex-melnyk/react-native-multibar#34]
I'm getting " Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`" as a warning. How to remove that?

Is there any prop to set it explicitly?

**Comment by alex-melnyk** [comment]
> I'm getting " Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`" as a warning. How to remove that?
> 
> Is there any prop to set it explicitly?

In what place it raises?

**Comment by lakinduakash** [comment]
It is coming from in `Anonymous (at BottomTabBarWrapper/​index.js:15)`

**Comment by alex-melnyk** [comment]
All animation codes use `useNativeDrive: false` property, so it might be your own component.
Investigate your code, maybe you'll find some issues.
