### ISSUE TITLE
Is MultiBarProvider able to set extrasVisible to true or false?

### ISSUE THREAD

**Issue by brendan1809** [alex-melnyk/react-native-multibar#35]
I wanted to dismiss the multibar when i am navigating to other page

**Comment by alex-melnyk** [comment]
How do you do navigation to other pages? If you could get MultiBarContext in these places you can invoke setter setExtrasVisible.

**Comment by brendan1809** [comment]
When pressing once of the button on the bottom tab bar , is there any example to use the MultiBarContext ?

**Comment by alex-melnyk** [comment]
@brendan1809 please see an example https://github.com/alex-melnyk/react-native-multibar/blob/master/example/App.tsx
