### ISSUE TITLE
Show Modal on Tab Item Press

### ISSUE THREAD

**Issue by destinybonavita** [alex-melnyk/react-native-multibar#36]
I'm using `useState()` to show and hide a modal with a multi bar icon, but when the modal is showing, the "wheel" of icons is not going away.

**Comment by destinybonavita** [comment]
I was attempting to `useContext` to hide the extras but didn't have any luck since the modal isn't a child of the `MultiBarContext`

**Comment by alex-melnyk** [comment]
I'm not that I understand what exactly going in your code, could you provide a code?

**Comment by destinybonavita** [comment]
I tried creating an [example of the problem](https://snack.expo.io/@destinybonavita/multibar-example) but it isn't happening in the snack for some reason--I'll continue to attempt to reproduce it.
