### ISSUE TITLE
How can I make Icon wrapped in MultiBarButton to rotate 45 degree ?

### ISSUE THREAD

**Issue by YajanaRao** [alex-melnyk/react-native-multibar#40]
The icon in close and open state appears the same as it rotates 180 degree. How can I make the icon to turn 45 degree so that It appears as close icon ?

**Comment by alex-melnyk** [comment]
@YajanaRao please see an example https://github.com/alex-melnyk/react-native-multibar/blob/master/example/App.tsx.
