### ISSUE TITLE
Cannot find module 'react-native-multibar' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by seyaobey-dev** [alex-melnyk/react-native-multibar#50]
I've just downloaded `react-native-multibar: ^1.1.5` in my typescript expo app. When I import it to use in my component, I get the above error:
```
Cannot find module 'react-native-multibar' or its corresponding type declarations
```

**Comment by sam-freestyle** [comment]
Hey, I had a similar issue with expo so I had a look at the [expo example](https://github.com/alex-melnyk/tabber-expo) from the readme that is still working. The example is using react-native-multibar@1.0.5 so I changed my version to that and got it working. Hope that helps?

**Comment by alex-melnyk** [comment]
@sam-freestyle @seyaobey-dev hey folks, I do not support react-native modules anymore, feel free to create PR then I can provide a fixed version.
