### ISSUE TITLE
Make Another element untouchable except the showed button

### ISSUE THREAD

**Issue by setanallas** [alex-melnyk/react-native-multibar#8]
i'm following your tutorial from itnext.io its work very well, but i want another element except 3 showed button(rocket, home, archive) is untouchable so there's no option to click another place except thats 3 button or outside it to hide them again.

**Comment by alex-melnyk** [comment]
Not sure that I understand what do you want to implement, do you want to put behind the actions some other element which will be as a trigger to hide actions?
